on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the user that starts the workflow'
        required: true
        default: 'Paolo Salvatori'

name: Metering Sample ARM Template Deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Print user name
    - run: |
        echo "Workflow started by ${{ github.event.inputs.logLevel }}"

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_SAMPLE_RG }}
        template: ./arm/templates/sample/azuredeploy.json
        parameters: location=WestEurope

      # output containerName variable from template
    - run: echo "WebAppName=${{ steps.deploy.outputs.webAppName }}"